davidgiven/fluxengine

.gitignore, tools/brother120tool.cc
Brother 120k starting sector addresses are actually two bytes long.  I'm sure there are prettier C++ish ways to express this, but there you go.
=> File sector start addresses are 16 bits long (well, maybe only 9)

lib/bytes.h, lib/ibm/decoder.cc
Old C++ compilers don't like static_assert without a message.
=> Fix build error on very old systems.

meson.build
Necessary changes to meson.build that makes fluxengine build under FreeBSD.
=> fix meson.build so that fluxengine compiles under FreeBSD

lib/decoders/decoders.cc, lib/decoders/decoders.h, lib/reader.cc, lib/victor9k/decoder.cc, lib/victor9k/victor9k.h
This is necessary for the Victor 9k; we now have _much_ better decoding for this platform.
=> Add the ability for decoders to specify their own clocks.

.travis.yml, lib/image.cc, lib/reader.cc, lib/sectorset.cc, lib/sectorset.h
This fixes a nasty memory corruption issue in replace_sector where if a sector got reread it would sometimes be freed in memory before we'd finished using it --- yes, another C++ object lifecycle issue. 
Weirdly this worked fine on Linux but would crash Cygwin.
Fixes: #66
=> Fix memory corruption issue when replacing sectors.

.appveyor.yml, .travis.yml, Makefile, doc/building.md, lib/fluxsource/kryoflux.cc, mkninja.sh
The Windows client now builds via appveyor, and is a stock Windows binary rather than the Cygwin thing previously.
=> Use mingw32 to build the Windows client, removing the cygwin dependency.

doc/disk-c64.md, doc/using.md, lib/imagewriter/d64imagewriter.cc, lib/imagewriter/imagewriter.cc, lib/imagewriter/imagewriter.h, mkninja.sh, src/fe-readc64.cc
This allows C64 disks to be captured into a format which can be used in emulators.
=> Add write-only support for D64 disk images.

lib/globals.h, lib/imagereader/imagereader.cc, lib/imagereader/imagereader.h, lib/imagewriter/imagewriter.cc, lib/imagewriter/imagewriter.h, lib/reader.cc
Also refactor the way image formats are handled to make it generally cleaner (could be cleaner sitll, though).
Fixes: #96
=> Validate image extensions before reading, not after.

doc/using.md, lib/flags.cc, lib/flags.h, mkninja.sh, src/fe-fluxtoscp.cc, src/fe-scptoflux.cc, src/fluxengine.cc, src/scp.h
Add support for importing and exporting Supercard Pro SCP files (via `fluxengine convert`). Export is extremely untested and a bit dubious due to semantic mismatches (flux files contain features which can't be represented in scp); import's a bit more robust.
=> Add very beta support for scp import and export

arch/ibm/decoder.cc, lib/decoders/decoders.cc, lib/decoders/fluxmapreader.cc, lib/reader.cc
This is a _workaround_ to an issue with the new sampler where it appears to introduce a bit of noise to the pulse lengths. Sometimes this noise can spoof MFM marker bytes in the sync sequence before a record, causing the record's clock to be misdetected (and therefore discarded).
This fix just increases the length of the detection sequence. It doesn't get rid of the noise, which we should really look into, but it does make HD disks read again.
=> Fix an issue where HD IBM disks can't be read

lib/bytes.cc, lib/bytes.h, lib/imagewriter/imgimagewriter.cc
When writing images, use the sector size in the spec rather than the actual data size, to avoid problems with multipart formats like the Amiga.
Fixes: #154
=> Fix stray bytes at the end of images

arch/amiga/decoder.cc, lib/reader.cc
The Amiga disk checksum algorithm is trash; I'm seeing a lot of spurious false positives, including a completely truncated sector being marked as good (because the checksum of 00 00 00 00... is 0). Plus, two bit errors in the same sector can cancel out and not be detected.
=> Fix some issues causing corruption when reading Amiga disks

arch/mx/decoder.cc, src/fe-scptoflux.cc
=> Fix a crash when decoding MX disks if advanceToNextRecord finds no records in a track.

arch/macintosh/decoder.cc
I was looking at the wrong bit of the side byte. Sigh.
Ref: #170
=> Make Mac double-sided disks work.

arch/macintosh/decoder.cc, doc/disk-macintosh.md, doc/using.md, lib/bytes.h, lib/imagewriter/diskcopyimagewriter.cc, lib/imagewriter/imagewriter.cc, lib/imagewriter/imagewriter.h, mkninja.sh
This adds support for writing Mac triangular GCR images to DiskCopy 4.2 files, which most emulators support.
Fixes: #13 See: #73
=> Add support for exporting to DiskCopy 4.2 Mac disk image

FluxEngine.cydsn/main.c, lib/fluxsink/fluxsink.h, lib/fluxsink/hardwarefluxsink.cc, lib/fluxsource/fluxsource.h, lib/fluxsource/hardwarefluxsource.cc, lib/reader.cc, lib/reader.h, lib/usb/fluxengineusb.cc, lib/usb/usb.h, lib/writer.cc, lib/writer.h, protocol.h, src/fe-readmicropolis.cc, src/fe-rpm.cc
Feel free to rip this apart. I would have discussed first, but things sort of fell into place and then it actually worked the first time it compiled...
Write support is untested, but that is the purpose and real goal. I hadn't added write support for Micropolis because the writes need to be aligned to the start of the track. I have not tested with retro hardware, but I have tested with the Micropolis support I added to FlashFloppy with some local changes to improve index timing (based on logic analyzer). It doesn't really impact reads much, but it appears to be working as `rpm` now produces consistent and correct results and things like `--sync-with-index true --revolutions .9` produce properly-aligned errors.
It'll be at least a month until I have access to Micropolis hardware again, for …
=> Add firmware support for hard sectors

doc/disk-atarist.md, doc/disk-ibm.md, lib/imagereader/imagereader.cc, lib/imagewriter/imagewriter.cc, mkninja.sh, src/fe-readatarist.cc, src/fe-writeatarist.cc, src/fluxengine.cc
This PR addresses #201.
It adds a new write option for creating Atari ST disks and registers the standard `.st` file extension so disk images can be used without having to rename them first. The standard IBM writer is used but many of the options are preset for ST disks (no IAM, fixed clock rates / speeds etc.).
Atari ST disks can be written using:
```
fluxengine write atarist --st-preset-820 -i my-disk-image.st 
```
The following format presets are available:
flag | format
-|-
--st-preset-360 | 360kB disk (1 side, 80 tracks, 9 sectors)
--st-preset-370 | 370kB disk (1 side, 82 tracks, 9 sectors)
--st-preset-400 | 400kB disk (1 side, 80 Tracks, 10 sectors)
--st-preset-410 | 410kB disk (1 side, 82 tracks, 10 sectors)
--st-preset-720 | 720kB disk (2 sides, 80 tracks, 9 sectors) …
=> Write Atari ST formats

arch/ibm/encoder.cc, arch/ibm/ibm.h, src/fe-writeibm.cc
According to https://github.com/Distrotech/fdutils/blob/master/src/mediaprm there are some obscure disk drives out there that expect the sides 0 and 1 to be swapped (search for "swapsides"). We are talking about
- Commodore 1581 3.5" Disk Drive
- CMD FD-2000 (and FD-4000)
- Thomson TO7
Remark: I know nothing about the last one and so I don't know if it uses IBM encoding at all. But the Commodore related drives above do use IBM encoding
So for those special cases the IBM writer needs another parameter to deal with them, I came up with "swapSides" (bool).
The big question is: Is this now cumbersome for all those "ordinary" cases where presets have to provide a false value for swapSides - like for example the Atari ST presets in the other Pull Request.
=> added parameter swapSides to IBM encoder

arch/ibm/encoder.cc, src/fe-writeibm.cc
Turns out that gap3 for 1440kB disks was wrong, and with the firmware fix, tracks no longer fit on a 200ms disk.
=> Fix the timing when writing IBM 1440kB disks.

src/fe-writeibm.cc
Hi,
Now this change is just a proposal - in two ways:
First, my preset for Commodore 1581 might not fit in well in this file - maybe it should get its own source file. (Especially as in a couple of days/weeks I will come up with a preset for CMD FD-2000 once I have found somebody who owns one and can confirm that the preset is ok. Some details regarding FD-2000 are in #107)
Secondly, the gap values of the 1581 preset are good enough for me and my tests with a real 1581 drive but might be matter of change once somebody reviews them / looks at diagrams, etc.
So this is just the current state of things and if you want - merge it, if not, it's ok for me - I can play with my 1581 images locally anyway.
=> Adding preset for Commodore 1581 (cbm1581) to IBM writer frontend

doc/using.md, lib/imagereader/imagereader.cc, lib/imagereader/imagereader.h, lib/imagereader/imdimagereader.cc, mkninja.sh, src/fe-writeibm.cc
Hello David,
Because i wanted to write imd files natively from fluxengine, i added a IMD image reader.
After reading the IMD image the reader presents what it has read to assist with determining the writer settings and options.
Greetings Wybren
=> Add IMD image reader and fix bug in ibm-preset-720

doc/disk-brother.md, doc/using.md, lib/dataspec.cc, lib/dataspec.h, lib/flaggroups/fluxsourcesink.cc, lib/flaggroups/fluxsourcesink.h, lib/fluxsink/fluxsink.h, lib/fluxsink/hardwarefluxsink.cc, lib/fluxsource/fluxsource.h, lib/fluxsource/hardwarefluxsource.cc, lib/imagereader/imgimagereader.cc, lib/reader.cc, lib/writer.cc, mkninja.sh, src/fe-analysedriveresponse.cc, src/fe-fluxtoau.cc, src/fe-fluxtovcd.cc, src/fe-seek.cc, tests/dataspec.cc
This adds 40-track support via an option to tell the hardware source/sink that the drive is 40-track, and a double-step option for images.
=> Better 40-track support.

src/fe-readibm.cc
For reading:
--ibm-preset-360 - Read a 5.25" 360kB disk in a 48tpi drive.
--ibm-preset-360-96tpi - Read a 5.25" 360kB disk in a 96tpi
drive.
--ibm-preset-1200 - Read a 5.25" 1.2MB disk.
For writing:
--ibm-preset-360 - Write a 5.25" 360kB disk in a 48tpi drive.
--ibm-preset-1200 - Write a 5.25" 1.2MB disk in a 96tpi drive.
Test:
Test reading and writing using a Teac FD-55GFR-571 96tpi drive.
Test reading and writing using an Alps DFC222B05A 48tpi drive.
Fixes davidgiven/fluxengine#189
=> Add presets for 5.25" IBM PC floppies.

src/fe-writeibm.cc
I wanted to create a FreeDOS boot floppy for an old Pentium III motherboard I had recently salvaged, but had the Teac FD-55GFR I'd bought 30 years ago for my first x86 box and some double-density floppies purchased NIB from an eBay seller.  (My longer-term interest in the FluxEngine is interoperation with the Apple II, but I'm just getting started with it.)  I'm not sure if there's a command-line incantation that sets up all the options just right to write 5.25" floppies, but this PR adds some presets for the common formats.  Separate options handle writing 360K disks in either double-density or high-density drives, and I included a 720K "quad-density" option (80 double-density tracks per side written in a high-density drive) that I used for cheap backups back in the day.  
So far, I've …
=> add write support for various 5.25" formats

FluxEngine.cydsn/main.c, arch/northstar/decoder.cc, arch/northstar/encoder.cc, arch/northstar/northstar.h, doc/disk-northstar.md, lib/decoders/fluxmapreader.h, lib/imagereader/imagereader.cc, lib/imagereader/imagereader.h, lib/imagereader/nsiimagereader.cc, lib/imagewriter/imagewriter.cc, lib/imagewriter/imagewriter.h, lib/imagewriter/nsiimagewriter.cc, lib/reader.cc, lib/reader.h, mkninja.sh, src/fe-readnorthstar.cc, src/fe-writenorthstar.cc, src/fluxengine.cc
North Star Floppy disks use 10-sector hard sectored disks with either FM
or MFM encoding.  They may be single- or double-sided.  Each of the 10
sectors contains 256 (FM) or 512 (MFM) bytes of data.  The disk has 35
cylinders, with tracks 0-34 on side 0, and tracks 35-69 on side 1.
Tracks on side 1 are numbered "backwards" in that track 35 corresponds
to cylinder 34, side 1, and track 69 corresponds to cylinder 0, side 1.
The North Star sector format does not include any head positioning
information.  As such, reads from North Star floppies need to by
synchronized with the index pulse, in order to properly identify the
sector being read.  While there is a command line option:
--sync-with-index, that does this, the North Star reader forces this
behavior by default.
Due to the nature of the …
=> Add support for North Star hard-sectored floppies.

.github/workflows/ccpp.yml, .github/workflows/release.yml, Makefile
It turns out I'd managed to leave out -static, producing dynamic binaries that didn't work without all the additional libraries being installed.
Fixes: #265
=> Make the Windows build static again.

doc/building.md
When building under Windows, the mingw-w64-i686-protobuf support
package is required.
=> Add mingw-w64-i686-protobuf to list of packages

lib/fluxsink/hardwarefluxsink.cc, lib/fluxsource/hardwarefluxsource.cc
The drive RPM measurement fails about 3% of the time.  Retry up to
five times until it succeeds, and exit with an error if it doesn't.
=> Perform retries when calculating drive RPM.

arch/c64/c64.h, arch/c64/encoder.cc, lib/imagereader/d64imagereader.cc, lib/imagereader/imgimagereader.cc
This should hopefully make writing C64 disks on 80-track drives work again.
Fixes: #288
=> Fix writing C64 disks

.github/workflows/ccpp.yml, Makefile, lib/usb/greaseweazleusb.cc
The USB protocol has been frozen, so all versions above or equal to 24 can be treated the same.
Fixes: #297
=> Support GreaseWeazle versions above 24.

lib/flags.cc
It turns out that the default config settings were being discarded, leading to problems.
See: #303 #307
=> Properly merge in the default settings.

arch/ibm/decoder.cc, arch/ibm/ibm.proto, lib/encoders/encoders.h, src/formats/atarist360.textpb, src/formats/atarist370.textpb, src/formats/atarist400.textpb, src/formats/atarist410.textpb, src/formats/atarist720.textpb, src/formats/atarist740.textpb, src/formats/atarist800.textpb, src/formats/atarist820.textpb, src/formats/commodore1581.textpb
This was causing the commodore1581 and all the atari formats not to work properly.
See: #307
=> Fix swap_sides on the IBM encoder/decoder.

src/formats/commodore1581.textpb
=> The 1581 format doesn't need swap_sides.

arch/ibm/decoder.cc, arch/ibm/encoder.cc, arch/ibm/ibm.proto, lib/decoders/decoders.cc, src/formats/atarist360.textpb, src/formats/atarist370.textpb, src/formats/atarist400.textpb, src/formats/atarist410.textpb, src/formats/atarist720.textpb, src/formats/atarist740.textpb, src/formats/atarist800.textpb, src/formats/atarist820.textpb, src/formats/commodore1581.textpb
On the encoder, it affects which logical side is being written to which physical side. On the decoder, it modifies the logical side bit in the sector header itself. This means that typically you would set it on the encoder but _not_ on the decoder.
=> swap_sides isn't symmetrical for the encoder and the decoder

scripts/encodedecodetest.sh
Looks like a typo, that would have had mostly the intended effect.
=> Redirect dd to stdout instead of file '1'

lib/fluxsink/scpfluxsink.cc, lib/fluxsource/scpfluxsource.cc, lib/scp.h, lib/utils.h
This prevents uninitialized memory reads for files with many
revolutions. See #322.
=> scpfluxsource: Support more than 5 revolutions

mkninja.sh, src/formats/ibm1232.textpb
This format is used by the PC-98 and Sharp X68000 series.
3.5" disks are spun at 360rpm to match the clock rate of 5.25".
=> Add Japanese PC 1.2MB format.

lib/usb/greaseweazleusb.cc
Pin 2 should be set high when high density is selected.
=> Fix inverted density select in Greaseweazle driver.

doc/using.md, lib/imagereader/imagereader.cc, lib/imagewriter/imagewriter.cc
This is a common extension for Sharp X68000 bare disk images.
=> Add alias for XDF image files.

lib/imagereader/dimimagereader.cc, lib/imagereader/fdiimagereader.cc
The computation for size accidentally included header size.
=> Fix reported size of DIM and FDI images.

doc/using.md, lib/imagereader/d88imagereader.cc, lib/imagereader/imagereader.cc, lib/imagereader/imagereader.h, lib/imagereader/imagereader.proto, mkninja.sh
This implements a subset of D88, only supporting the first floppy
in an image. It only supports images with equal sector sizes,
equal numbers of sectors per track, and no bad sectors.
=> Add minimal D88 image format reader.

doc/using.md, lib/imagereader/d88imagereader.cc
This supports varying sector sizes, counts, and modulation on
a per-track basis. It also supports writing sectors in the
original order.
=> Use per-track encoding specified in D88 files.

lib/proto.cc
This is most certainly a typo.
Also it could be nice to have the long-forms of "y" and "n" available as possible options as well
=> Fix a small typo in proto.cc

arch/northstar/decoder.cc, lib/imagewriter/nsiimagewriter.cc
Similar to Micropolis, the North Star decoder was broken by the PLL update.
Fix it and also fix the image size output in the informational message in nsiimagewriter.
Here are [example North Star flux files](https://www.dropbox.com/s/eks28s8dwsal04a/northstar_flux.zip?dl=0)
There is one each of 87.5K SSSD, 175K SSDD, 350K DSDD.
Thanks,
Howard
=> Fix North Star after decoder update

lib/imagereader/d88imagereader.cc
It's no longer needed to be this strict.
=> Remove per-track sector check from D88.

mkninja.sh, src/formats/n88basic.textpb
This isn't really intended to be used directly (bare images are
normally .d88 etc) but is useful for testing the FM encoder.
=> Add ibm_n88basic format.

lib/fluxsink/fluxsink.proto, lib/fluxsink/scpfluxsink.cc
There were a couple of problems that needed to be fixed:
- Fluxmaps can be produced with zero index pulses by encoders.
This is somewhat ambiguous but it's assumed that this means there
is exactly one revolution.
- The SCP unindexed mode wasn't properly supported, as it should
create equal-length revolutions not aligned to indexes. However,
fluxmaps don't contain any information on rotation speed. Therefore,
drop the ability to create unindexed SCPs and slightly change the
meaning of the option to not include pre-index data.
- Real flux reads can potentially produce duplicate index pulses.
Avoid creating zero-length revs.
- Fix off-by-one error for rev count.
=> Fix SCP writer to always write complete revolutions.

lib/usb/serial.cc
Per #393 FluxEngine can not open the serial port when COM port number is greater than COM9.
Windows requires the use of the DOS UNC path name for COM ports greater than COM9.
Fix: Prefix the port name with \\\\.\\
=> Windows: Support serial ports > COM9

lib/reader.cc
The conflicting sector error message incorrectly displays the track instead
of the sector in conflict.  Fix by removing unused track and head arguments,
displaying only the sector in conflict.
=> reader: Fix conflicting sector error message.

doc/using.md, lib/fluxmap.cc, lib/fluxmap.h, lib/fluxsink/fluxsink.proto, lib/writer.cc
Note that this does not affect the decoder used for verify,
but at least for tame rescaling the decoders are still able to
lock.
This is a precursor to automatic scaling via the disk speed
measurement.
=> Add option to rescale flux sink pulses. 

README.md, doc/disk-victor9k.md, mkninja.sh, src/formats/victor9k_ds.textpb, src/formats/victor9k_ss.textpb
Hi David,
Thanks for your help earlier. Here's a cleaner re-take on Victor9k double sided disks. I spent a lot of time iterating through what seemed like a bug in the encoder/decoder but was really a demonstration of my lack of bit-shifting skills. 
One note, I'm making an intentional change with track 48. The documentation shows it in zone 4 with 15 sectors and a speed of 187.6 original_period_ms. It actually is in zone 5 with 14 sectors and a speed of 175.3. I'm basing that off the zone organization I'm seeing in the BIOS and the format.com code. The mame code also makes this same correction to what's a bug in the documentation. I've reflected that change on the single sided disks also. 
This all seems to work fine when reading physical media to .img files and .flux files. I can then …
=> Victor9k Double Sided Support

.github/workflows/ccpp.yml, lib/usb/greaseweazleusb.cc, lib/usb/serial.cc, lib/usb/usb.cc, lib/usb/usbfinder.cc
hiya! im making a generic arduino-compatible floppy disk read/write library and one of the modes is 'greaseweazle compatibility' - this PR makes it so that fluxengine can successfully detect USB CDC serial ports when there is no exact VID/PID match, fixes a small packing bug in readflux, and also makes generic CDC windows 'activate' by enabling the DTR line. i also added zip upload on PR so folks can test without a release/build.
1) update CI to add zip on commit for quick testing
2) fix gw readflux command (should be 8 bytes long but was packed as 10)
3) add support for non-gw VID/PID (generic serial port that is gw compatible)
4) manually set/clear DTR on serial port devices - this seems to be essential for tinyusb/arduino CDC
not tested with a gw but ought not to have broken anything! …
=> add generic gw-compatible support

doc/using.md, lib/fluxsource/fluxsource.proto, lib/reader.cc
This actually scales by the reciprotal of the flux sink, to
allow the same value to be set for both options.
=> Add option to rescale flux source pulses.

lib/usb/greaseweazleusb.cc
This substantially speeds up read and verify operations, allowing
only 1.2 revs rather than 2 revs to be read.
Fixes #426
=> Support time-based reads for Greaseweazle V24+.

lib/fluxsource/fl2fluxsource.cc
=> Don't crash when trying to read flux from a fl2 file where there isn't any.

lib/sector.h, src/formats/brother120.textpb, src/formats/brother240.textpb
This can cause glitchiness with out-of-bound values, leading in total output failure.
Fixes #434
=> Don't use signed values for track/sector/side values

lib/imagereader/d88imagereader.cc, lib/imagereader/dimimagereader.cc, lib/imagereader/fdiimagereader.cc
- the DIM image reader now sets up the decoder, allowing writes to be verified
- the readers which do autoconfiguration will set the head and cylinder ranges where appropriate
Fixes: #424
=> Fix some autoconfigure issues.

lib/imagereader/d88imagereader.cc
This assumes a 360rpm drive, and double stepping.
If fluxengine supports the concept of 40 vs 80 track drives in the
future, it might make sense for this to assume a 300rpm drive
instead.
=> D88: Add 2D (40 track double density) support.

lib/fluxsink/scpfluxsink.cc, lib/scp.h
According to version 2.2 of the [SCP image specification at cbmstuff.com](https://www.cbmstuff.com/downloads/scp/scp_image_specs.txt) the number of Track Data Entries for a floppy can be up to 168, so that up to 84 tracks can be recorded (e.g., fluxengine -c 0-83).
> BYTES 0x10-0x2AF (for floppy image files) are a table of longwords with each entry being an offset to a Track Data Header (TDH) for each track that is stored in the image.  The table is always sequential.  There is an entry for every track, with up to 168 entries supported for floppy disks.  This means that floppy disk images of up to 84 tracks with sides 0/1 are possible.
Additionally, instead of segfaulting if a too-large number of tracks (e.g. -c 0-84) is used, print a message and continue.
=> Support 84-track SCP files

arch/aeslanier/decoder.cc, arch/amiga/decoder.cc, arch/apple2/decoder.cc, arch/brother/decoder.cc, arch/c64/decoder.cc, arch/f85/decoder.cc, arch/fb100/decoder.cc, arch/ibm/decoder.cc, arch/macintosh/decoder.cc, arch/micropolis/decoder.cc, arch/mx/decoder.cc, arch/northstar/decoder.cc, arch/tids990/decoder.cc, arch/victor9k/decoder.cc, arch/zilogmcz/decoder.cc, lib/bytes.cc, lib/bytes.h, lib/decoders/decoders.cc, lib/decoders/decoders.h, scripts/encodedecodetest.sh
This reworks all the decoders to avoid seeking inside the fluxmap when doing reads. This requires resetting the FluxDecoder, which loses any pending state, resulting in bad reads for (some) formats which don't have gaps between sectors --- the DVK MX is the main victim.
Closes: #438
=> Prevent bad reads on gapless formats.

lib/usb/serial.cc
The addition of the new `tcsetattr` call fixes a problem where interrupting fluxengine during a flux read will leave data in the device and/or Linux's serial buffers, so that the next invocation of fluxengine will fail similar to
```
Error: command returned garbage (0x27 != 0x0 with status 0x31)
```
(the specific value differs because it's actually flux data)
Merely changing the existing `tcsetattr` call to specify `TCSAFLUSH` was not enough; moving it after the 200ms pause seems to be enough.
Note that it doesn't seem feasible in our USB stack to make DTR reset the device, since that would take down the USB stack and require a fresh USB connection.
The addition of the special case for `rlen == 0` in read is for when the GW-compatible board is reset or crashes and usb-disconnects during a …
=> Some quality of life improvements for Adafruit generic GW-compatibles

README.md, arch/ibm/decoder.cc, arch/ibm/ibm.proto, doc/disk-atarist.md, src/formats/atarist360.textpb, src/formats/atarist370.textpb, src/formats/atarist400.textpb, src/formats/atarist410.textpb, src/formats/atarist720.textpb, src/formats/atarist740.textpb, src/formats/atarist800.textpb, src/formats/atarist820.textpb
It turns out that some ST formatter programs add an extra IDAM record with sector number 66 to the disk, which needs filtering out.
=> Fix the Atari ST profiles

tools/upgrade-flux-file.cc
The upgrade-flux-file utility does not work properly under Windows.  It runs into an error because the open database file cannot be renamed in-place.
Close the database and remove the input file prior to renaming.
Tested this change on Windows, MacOS, Linux.
=> upgrade-flux-file: Fix for Windows

arch/amiga/encoder.cc, arch/brother/encoder.cc, arch/c64/encoder.cc, arch/ibm/encoder.cc, arch/macintosh/encoder.cc, arch/micropolis/encoder.cc, arch/northstar/encoder.cc, arch/tids990/encoder.cc, arch/victor9k/encoder.cc, lib/decoders/decoders.cc, lib/decoders/decoders.h, lib/encoders/encoders.h, lib/flux.h, lib/globals.h, lib/image.cc, lib/image.h, lib/logger.cc, lib/logger.h, lib/reader.cc, lib/sector.cc, lib/sector.h, lib/writer.cc
This makes them intrinsically thread safe as we don't need to worry about mutations any more. Ownership is nearly always done with std::shared_ptr now, which is thread safe.
=> Make the internal disk data structures all const.

lib/fluxmap.cc
Fluxmap::split() creates a 0-length Fluxmap if the Fluxmap
begins with F_DESYNC.  Fix this by not doing push_back()
if a F_DESYNC is encountered at the start of the Fluxmap.
=> fluxmap: Don't push_back() if Fluxmap begins with F_DESYNC.

arch/micropolis/decoder.cc, arch/northstar/decoder.cc
seekToPattern() can skip the index hole if it doesn't find the
SYNC pattern.  If this happens too close to the end of the flux
stream, it can result in a conflicted sector.  In this case,
discard the sector.
This makes a small improvement for #328 on some disks.
=> Improve hard sector decode

doc/disk-ibm.md, mkninja.sh, src/formats/rx50.textpb
According to my source [https://www.cbmstuff.com/forum/showthread.php?tid=634] the format of RX-50 is
* single sided
* 80 tracks
* 10 sectors per track
* 96 tpi (tracks per inch)
* 300 rpm (revolutions per minute)
* 250 KHz data rate
I have a disk labeled
```
BL-T540E-MC
CZUFDE0 MICRO PDP-11
USER TESTS
© 1983, 1894
DIGITAL EQUIPMENT CORP.
```
and stamped 14131.
The image read all sectors and the content looks plausible.  `strings` on it says things like
```
$ strings rx50.img  | grep -i pdp
; This file implements the USER FRIENDLY Diagnostic for the MICRO PDP11 & 11/73
```
however, I don't have an emulator or other system to use the disk image with so
I can't 100% vouch for the image being complete and correct.
=> Add support for PDP-11 RX-50 disks

.gitignore, README.md, arch/apple2/apple2.h, arch/apple2/apple2.proto, arch/apple2/encoder.cc, doc/disk-apple2.md, lib/encoders/encoders.cc, lib/encoders/encoders.proto, mkninja.sh, src/formats/apple2.textpb
This is tested with encodedecodetest.sh but is not tested on HW yet. It's likely that the sector order (interleave) doesn't match real systems.
=> Add apple2 encoder

Makefile, arch/apple2/decoder.cc
Sometimes there's a 1-bit gap between APPLE2_DATA_RECORD and the data itself.  This has been seen on real world disks such as the Apple II Operating System Kit from Apple2Online.  However, I haven't seen it described in any of the various references.                    
This extra '0' bit would not affect the real disk interface, as it was a '1' reaching the top bit of a shift register that triggered a byte to be available, but it affects the way the data is read here.                                  
With this change, and a separate program to manipulate an image between physical order and logical DOS3.3 order, I was able to verify that the "Apple II Operating System Kit Apple DOS 3.3" disk that I imaged with FluxEngine is 1 bit different from the image available at …
=> apple2: Comment decoder, add fix/workaround for stray 0 at start of sector data

arch/victor9k/encoder.cc, arch/victor9k/victor9k.h, src/formats/victor9k_ds.textpb, src/formats/victor9k_ss.textpb
Hi David,
I've tested this with both SS and DS disks on two different physical machines and it works reliably. I can also image these disks with an Applesauce, so I think we have a winner. I'm not a C++ guy, so apologies if the write_gap() isn't idiomatic. I'm just trying to write I/O encoded zeros. I tried using your suggestion of fillBitmapTo() and that didn't work, but this solution does. 
Thanks much for your help with all this. I've tested writing about 5 different disks at this point, so I'm feeling relatively good.
Paul
=> works in physical victor 9000 machine

lib/bytes.cc, lib/bytes.h, lib/fl2.proto, lib/fluxmap.cc, lib/fluxmap.h, lib/fluxsink/aufluxsink.cc, lib/fluxsink/fl2fluxsink.cc, lib/fluxsink/fluxsink.h, lib/fluxsink/hardwarefluxsink.cc, lib/fluxsink/scpfluxsink.cc, lib/fluxsink/vcdfluxsink.cc, lib/fluxsource/cwffluxsource.cc, lib/fluxsource/erasefluxsource.cc, lib/fluxsource/fl2fluxsource.cc, lib/fluxsource/fluxsource.cc, lib/fluxsource/fluxsource.h, lib/fluxsource/hardwarefluxsource.cc, lib/fluxsource/kryofluxfluxsource.cc, lib/fluxsource/scpfluxsource.cc, lib/fluxsource/testpatternfluxsource.cc, lib/reader.cc, lib/writer.cc, lib/writer.h, protocol.h, src/fe-inspect.cc, tests/bytes.cc
Currently multiple reads (i.e. on a retry) are stored in the flux bytestream with a F_DESYNC separator. This is problematic in various ways, as some of the decoders don't expect this and don't handle it properly (e.g. ones that keep track of the disk position).
This replaces this with storing multiple flux bytestreams properly plumbed throughout the system, including in the FL2 flux files. FluxSources now return an iterator which can be used to fetch all available reads (for FluxSources which support it).
Also needed: doing something sensible with multiple reads with rawread and rawwrite. And also the third-party flux files...
=> Refactor to deprecate F_DESYNC.

README.md, doc/disk-apple2.md, mkninja.sh, src/formats/appledos.textpb, src/formats/prodos.textpb
* Update documentation (note apple flux writing is a unicorn now even though this isn't quite true until #489)
* Fix DOS 3.3 mapping
* Add ProDOS (all versions) mapping
=> Upgrade Apple II writing to 'unicorn', fix & explain remapping

Makefile
If it's built as a GUI program, it doesn't work at all from the Windows CLI. Turns out that mingw doesn't use the normal Windows CLI interface to run programs, so this problem doesn't appear there.
Fixes: #501
=> Don't build the Windows CLI as a GUI program.

doc/greaseweazle.md, lib/usb/greaseweazle.h, lib/usb/usb.proto
Some folks may want to use interfaces besides PC/Shugart ones. Together with https://github.com/adafruit/Adafruit_Floppy/pull/15 and a hand wired board I'm able to read flux from an Apple Disk ][ (don't sweat the bad sectors, this floppy was written before I mostly got the bugs out of flux generating for apple2s)
I've also started a dialog with @kierf about allocating these disk-type numbers. However, we haven't settled the details yet. This actual working code may be useful in figuring out the way forward among all of us:
* https://github.com/keirf/greaseweazle/pull/171
Writing will have an additional wrinkle: The Apple2 stepping mechanism is designed so that it's possible to reach 3 intermediate positions between each of the ~35 data tracks. Because we hope to image protected floppies, …
=> Add support for the interfacing to an Apple Disk ][

lib/usb/greaseweazleusb.cc
Accumulate number of ticks returned in FLUXOP_SPACE so that they
count towards the total track time.
=> Greaseweazle: Fix RPM measurement in some circumstances.

doc/using.md, lib/imagewriter/d88imagewriter.cc, lib/imagewriter/imagewriter.cc, lib/imagewriter/imagewriter.h, lib/imagewriter/imagewriter.proto, mkninja.sh
Add D88 image writer.
This is currently a very minimal implementation and does not
support deleted sectors, CRC errors, etc.
=> Add D88 image writer.

README.md, dep/emu/UPSTREAM.md, dep/snowhouse/UPSTREAM.md, dep/stb/UPSTREAM.md
Some of the UPSTREAMs were unaccountably missing.
Fixes: #526
=> Update missing UPSTREAMs and the README.

.gitignore, Makefile
The support configuration variables are based on common conventions.
Default install prefix is `/usr/local`. Currently only the binaries are installed.
For packaging for a distro something along these lines would be used:
```
make install DESTDIR=/tmp/pkg-staging-directory PREFIX=/usr
```
The reason to have an install rule instead of handling that locally in each distribution is that if new binaries, data etc are added, there is only one location that has to be updated, rather than every distro noticing and updating their build rules.
I did not spread out the rules for this in the subdirectories, as writing the code just at the top level reduced the number of lines changed, but that might be possible (I'm not much of a Makefile-expert however. I generally use CMake or similar for my own …
=> Add install rule and fix some build system issues

lib/imagereader/d88imagereader.cc
The values used for 1.2MB HD disks are too narrow for the
PC-88's disk controller.
=> Add n88basic sector gaps to d88 reader for PC-88 DD disks.

lib/imagewriter/d88imagewriter.cc
This was failing to write the last sector in the image.
=> D88: Fix sector ID conditions when writing.

Makefile
This should avoid the weird error message if you use the default OSX make.
=> Error out if you're not using GNU Make 4.

lib/imagereader/d88imagereader.cc, lib/imagereader/nfdimagereader.cc
Partially fixes #603, it is still busted if the number of
tracks is specified larger than what is in the image, which
used to work.
=> D88/NFD: Add physical layout before adding sector.

lib/imagereader/d88imagereader.cc
This will effectively ignore the field length if it is shorter
than the sector size (or 0).
=> D88: Use the data length field to seek past any extra data.

lib/environment.cc
An environment manager bug would cause a segfault when resetting the environment.
Fixes: #610
=> Fix a crash when using the GUI.

Makefile, lib/fluxsink/scpfluxsink.cc, lib/layout.cc, lib/layout.h, lib/readerwriter.cc
A few places, including the SCP flux sink, were using the old range config fields rather than the new locations code, resulting in incorrect SCP headers.
Fixes: #593
=> Correct generation of SCP files.

extras/FluxEngine.app.template/Contents/MacOS/FluxEngine.sh
Use correct fallback variable for libs, not for frameworks. Also look for libs in MacPorts' default lib path /opt/local/lib, not only HomeBrew's
=> Library fallback path fixed & MacPorts compatible

.github/workflows/ccpp.yml, .github/workflows/release.yml, src/gui/build.mk
Thanks to dylibbundler, these should now have the right libraries and an edited executable in them.
Fixes: #625
=> Produce more correct OSX app bundles.

lib/vfs/brother120fs.cc, src/formats/brother120.textpb, src/formats/brother240.textpb
- images were read and written hopelessly wrong (due to bad sector skew)
- brother120 filesystems were poorly detected (not at all detected) and could cause crashes if you tried to use one on something which wasn't a brother120 filesystem.
=> Fix some nasty Brother bugs.

arch/micropolis/micropolis.proto
The disks are expected to contain 100,000 bitcells, so clock_period_us and rotational_period_ms need to align.
=> Micropolis: disk rotate period is 200 ms

extras/windows-installer.nsi
This fix corrects the product name shown on the initial installer page, as well as the name of the Desktop shortcut created so that it matches the name provided in the Uninstall script.
=> Fix incorrect product name in installer.

arch/micropolis/decoder.cc, arch/micropolis/encoder.cc, lib/encoders/encoders.cc
These changes should not impact reading/writing from real disks. This includes a bug fix to Fluxmap where it might miss a trailing interval when adding bits, as mentioned in #333.
With the Fluxmap bug fixed, the encoder now includes index pulses in its output. The decoder was relaxed to allow reading precisely one track.
We don't actually add an encodedecodetest for micropolis, though, because the SCP encoder is unhappy with so many revolutions.
=> Micropolis: Fix encoder and decoder to support encodedecodetest

Makefile
Protobuf added a dependency on absl and now pkg-config is incredibly slow. `pkg-config --libs protobuf` and `--cflags` each take around 1.5 seconds on my laptop. Running pkg-config only once reduces a 100% incremental build for 'make all' from 90 seconds to 3.2 seconds.
Unfortunately we will pay the 3 seconds every time we execute make, even for something that doesn't need protobuf.
=> Makefile: Eagerly run pkg-config for protobuf

Makefile, dep/libusbp/build.mk, dep/libusbp/src/dummy.c
Here is a minimal patch to make the non-gui executable compile on FreeBSD.
I created a "dummy.c" file for libusbp with sufficient entrypoints for compilation to succeed but all of them failing.
=> Make the non-gui executable build on FreeBSD

lib/sector.h
This should fix #696 and let gcc compile FluxEngine.
=> Fix const-correct/discards qualifiers error.

lib/usb/serial.cc
After calling SetCommState in setBaudRate DTR is no longer set. 
The amendment in this request clears and sets DTR again, like in the constructor.
=> Set DTR after calling SetCommState

lib/usb/serial.cc, lib/usb/serial.h
This is required by the Greaseweazle (and Adafruit Greaseweazle-compatible devices) to reset the protocol.
=> Correctly twiddle DTR on Linux/OSX when changing baud rates.

README.md, build.py, doc/applesauce.md, doc/using.md, lib/decoders/fluxmapreader.cc, lib/flags.cc, lib/fluxsource/fluxsource.proto, lib/fluxsource/testpatternfluxsource.cc, lib/globals.cc, lib/usb/applesauce.cc, lib/usb/applesauce.h, lib/usb/applesauceusb.cc, lib/usb/fluxengineusb.cc, lib/usb/greaseweazle.cc, lib/usb/greaseweazle.h, lib/usb/greaseweazleusb.cc, lib/usb/serial.cc, lib/usb/serial.h, lib/usb/usb.cc, lib/usb/usb.h, lib/usb/usb.proto, lib/usb/usbfinder.cc, lib/usb/usbfinder.h, tests/applesauce.cc, tests/build.py, tests/greaseweazle.cc
Currently, read only; I need to wait for the 3.0 firmware before I can make write support work.
=> Add basic support for Applesauce hardware.

src/formats/juku.textpb
There was a correction discussed at #795, but never implemented. Also find a non-copyrighted flux image of a Juku floppy in [the last message](https://github.com/davidgiven/fluxengine/issues/795#issuecomment-3219126881) of the discussion. And also fixed the links to refer to non GitHub versions of referred documents on public Internet (https://j3k.infoaed.ee/).
=> Correct Juku E5104 documentation
