davidgiven/fluxengine

.travis.yml
Makefile
lib/globals.h
meson.build

Ugh, C++14 on Travis is a pain.

Enable Travis-CI support.

---

lib/brother/decoder.cc
lib/reader.cc

...and, in fact, much better reads for any 40-track disk.

Fix bugs leading to drastically better 120kB Brother reads.

---

doc/aeslanier.md
doc/index.md
lib/aeslanier/aeslanier.h
lib/aeslanier/decoder.cc
lib/bytes.h
lib/crc.cc
lib/crc.h
lib/decoders/fmmfm.cc
lib/image.cc
lib/reader.cc
lib/sector.h
meson.build
src/fe-readaeslanier.cc

_Very_ experimental, and probably wrong.

Add incredibly experimental support for the AES Superplus / Lanier No Problem

---

doc/index.md
lib/bytes.cc
lib/bytes.h
lib/fluxreader/sqlitefluxreader.cc
lib/reader.cc
lib/sql.cc
lib/sql.h
lib/writer.cc
meson.build
src/fe-update.cc
src/fe-upgradefluxfile.cc
tests/compression.cc

They're about half the size now. Also add in a properties table, proper versioning, type fields per data stream, and an upgrade system.

Flux files now compress their data.

---

README.md
doc/disk-fb100.md
lib/bytes.h
lib/crc.cc
lib/crc.h
lib/decoders/decoders.cc
lib/decoders/decoders.h
lib/fb100/decoder.cc
lib/fb100/fb100.h
lib/reader.cc
meson.build
src/fe-readfb100.cc

Add support for Brother FB-100 disks; plus some new bits of infrastructure.

Add Brother FB-100 support.

---

doc/disk-fb100.md
lib/bytes.cc
lib/bytes.h
lib/encoder.cc
lib/fluxmap.cc
lib/fluxmap.h
lib/fluxreader/kryoflux.cc
lib/fluxreader/kryoflux.h
lib/sector.cc
lib/zilogmcz/decoder.cc
src/fe-readzilogmcz.cc
src/fe-upgradefluxfile.cc
src/fe-writetestpattern.cc
tests/kryoflux.cc
tools/cwftoflux.cc

Parse the index markers from Kryoflux streams and, hopefully, put them in the right place.

Add index mark support to the Kryoflux reader.

---

.appveyor.yml
mkninja.sh
src/fe-cwftoflux.cc
src/fe-fluxtoau.cc
src/fe-fluxtovcd.cc
src/fluxengine.cc

Move some of the stray tools into the main client, for simplicity and binary size reasons.

Build cleanups

---

doc/using.md
lib/bytes.cc
lib/bytes.h
lib/imagewriter/imagewriter.cc
lib/imagewriter/imagewriter.h
lib/imagewriter/ldbsimagewriter.cc
lib/ldbs.cc
lib/ldbs.h
mkninja.sh
tests/ldbs.cc

Add basic support for outputting LDBS data files; these allow arbitrary geometries and checksum correctness flag information.

Add support for writing LDBS image files.

---

Makefile
doc/using.md
mkninja.sh
src/fe-scptoflux.cc
src/fluxengine.cc

This adds support for converting Supercard Pro scp files to flux.

Add conversion support for Supercard Pro scp files.

---

.appveyor.yml
src/fe-rpm.cc

Also, ship brother240tool with Windows releases.

Display RPM values correctly

---

arch/ibm/decoder.cc

Typo fix in FM_TRS80DAM2_PATTERN

---

lib/globals.h
lib/reader.cc
lib/visualiser.cc
src/fe-fluxtoscp.cc

It's been broken since forever.
Fixes: #173, #134

Fix the SCP exporter.

---

arch/micropolis/decoder.cc
arch/micropolis/micropolis.h
doc/disk-micropolis.md
mkninja.sh
src/fe-readmicropolis.cc
src/fluxengine.cc

Add Micropolis decoder

---

mkninja.sh
scripts/analysedriveresponse.py
src/fe-analysedriveresponse.cc
src/fluxengine.cc

This (plus the associated Python script) will generate a heatmap showing drive response at different pulse frequencies.

Add an analysis tool for checking drive response.

---

doc/building.md

Add missing zlib dependency.

---

src/fe-writeflux.cc

This doesn't work, and never has.
Fixes: #254

Fix writeflux to actually work.

---

src/readables/northstar.textpb
src/writables/northstar175.textpb
src/writables/northstar350.textpb
src/writables/northstar87.textpb

Tested read/write with 350K, 175K, and 87K disks.

Northstar: Fix configurations.

---

Makefile
doc/building.md
mkninja.sh

Fix some OSX build inelegancies.

---

src/fe-analyselayout.cc

modify available space (width and height) with subtraction of two times the border (up en down, and left and right)

Fix distorted picture

---

lib/imagewriter/nsiimagewriter.cc

North Star DOS provided an upgrade path for disks formatted as
single-density to hold double-density data without reformatting.  In
this case, the four directory blocks will be single-density but other
areas of the disk are double-density.  This cannot be accurately
represented using a .nsi file, so in these cases, we pad the sector to
512-bytes, filling with spaces.

Northstar: Handle mixed-density disks

---

arch/amiga/amiga.h
arch/amiga/encoder.cc
arch/brother/brother.h
arch/brother/encoder.cc
arch/c64/c64.h
arch/c64/encoder.cc
arch/ibm/encoder.cc
arch/ibm/ibm.h
arch/macintosh/decoder.cc
arch/macintosh/encoder.cc
arch/macintosh/macintosh.h
arch/macintosh/macintosh.proto
arch/northstar/decoder.cc
arch/northstar/encoder.cc
arch/northstar/northstar.h
arch/tids990/encoder.cc
arch/tids990/tids990.h
lib/encoders/encoders.cc
lib/encoders/encoders.h

Rework the encoders; also remove some stray flags that got left in during the big rework.

More refactoring and cleanup, this time of the encoders.

---

Makefile
arch/brother/encoder.cc
arch/ibm/encoder.cc
arch/macintosh/encoder.cc
arch/northstar/encoder.cc
arch/tids990/tids990.h
lib/encoders/encoders.cc
lib/flags.cc
lib/imagereader/imagereader.cc
lib/imagereader/imagereader.proto
lib/imagereader/imagereaderimpl.h
lib/imagereader/imgimagereader.cc
lib/imagewriter/imgimagewriter.cc
lib/proto.cc
mkninja.sh
scripts/commodore1541_test.textpb
scripts/encodedecodetest.sh
scripts/mac400_test.textpb
scripts/mac800_test.textpb
src/formats/atarist360.textpb
src/formats/atarist370.textpb
src/formats/atarist400.textpb
src/formats/atarist410.textpb
src/formats/atarist720.textpb
src/formats/atarist740.textpb
src/formats/atarist800.textpb
src/formats/atarist820.textpb

Add round-trip encode/decode tests for the formats which support them and fix issues brought up by them.

Overhaul the tests.

---

doc/building.md
doc/using.md
lib/proto.cc

- allow setting proto enum configuration options from the command line
- update documentation
Fixes: #327 #323

Assorted minor fixes.

---

Makefile
arch/ibm/decoder.cc
doc/disk-victor9k.md
lib/decoders/decoders.cc
lib/decoders/decoders.h
lib/decoders/decoders.proto
lib/decoders/fluxdecoder.cc
lib/decoders/fluxdecoder.h
lib/decoders/fluxmapreader.cc
lib/decoders/fluxmapreader.h
mkninja.sh
src/fe-inspect.cc
src/formats/victor9k.textpb

This ports the PLL algorithm from samdisk, producing much more reliable reads.

Rewrite the flux decoder to use a PLL-driven algorithm.

---

doc/using.md
lib/imagereader/dimimagereader.cc
lib/imagereader/imagereader.cc
lib/imagereader/imagereader.h
lib/imagereader/imagereader.proto
mkninja.sh

This format is common for Japanese PC floppy images.

Add DIM format reader.

---

doc/using.md
lib/imagereader/fdiimagereader.cc
lib/imagereader/imagereader.cc
lib/imagereader/imagereader.h
lib/imagereader/imagereader.proto
mkninja.sh

This format is common for NEC PC-98 disk images.

Add FDI format reader.

---

lib/imagereader/d64imagereader.cc
lib/imagereader/dimimagereader.cc
lib/imagereader/diskcopyimagereader.cc
lib/imagereader/fdiimagereader.cc
lib/imagereader/imagereader.cc
lib/imagereader/imagereader.h
lib/imagereader/imdimagereader.cc
lib/imagereader/imgimagereader.cc
lib/imagereader/jv3imagereader.cc
lib/imagereader/nsiimagereader.cc
lib/imagereader/td0imagereader.cc
lib/writer.cc
lib/writer.h
src/fe-write.cc

Refactor to allow image readers to specify the encoder/decoder formats, if desired.

---

arch/victor9k/decoder.cc
arch/victor9k/encoder.cc
arch/victor9k/victor9k.h
arch/victor9k/victor9k.proto
doc/disk-victor9k.md
lib/encoders/encoders.cc
lib/encoders/encoders.proto
lib/reader.cc
mkninja.sh
src/formats/victor9k.textpb
src/formats/victor9k_ss.textpb

Also fix a bunch of other issues and do cleanup.

Add a Victor 9000 encoder.

---

.github/workflows/ccpp.yml
lib/fl2.proto
lib/fluxsink/fl2fluxsink.cc
lib/fluxsink/fluxsink.cc
lib/fluxsource/fl2fluxsource.cc
lib/fluxsource/fluxsource.cc
mkninja.sh
scripts/encodedecodetest.sh
src/fe-upgradefluxfile.cc

Old flux files will be read (with a warning), and new ones will be written with the new format. The upgrader will upgrade them.

Make the new FL2 format the default.

---

lib/usb/greaseweazleusb.cc
lib/usb/serial.cc
lib/usb/serial.h
mkninja.sh

This pulls it out into a distinct class for use by other modules.

Refactor the serial port code.

---

src/formats/victor9k_ss.textpb

- sector IDs start at 0
Fixes: #389

Victor 9000 fixes

---

Makefile
lib/imagewriter/imgimagewriter.cc
mkninja.sh

Fix some minor build glitches and warnings.

---

doc/greaseweazle.md
lib/usb/greaseweazleusb.cc
lib/usb/usb.cc
lib/usb/usb.h
lib/usb/usb.proto

Add support for selecting the Shugart or IBMPC GreaseWeazle bus types.

---

Makefile

Add Make target to build compdb.

Add Make target to build compdb.

---

doc/using.md
lib/imagereader/imagereader.cc
lib/imagereader/imagereader.h
lib/imagereader/imagereader.proto
lib/imagereader/nfdimagereader.cc
mkninja.sh

This format is very similar to D88, but used mostly for PC-98
rather than PC-88.

Add NFD r0 image reader.

---

src/fe-write.cc

Add flag to skip verification during write.

---

src/fe-write.cc

This got broken by #436.
Fixes: #425

Fix --no-verify.

---

arch/amiga/amiga.h
arch/amiga/decoder.cc
arch/amiga/encoder.cc
lib/decoders/decoders.cc
lib/imagewriter/imagewriter.cc
lib/sector.h

In particular, the Amiga decoder was broken. I also found a bug in the Amiga encoder.

Fix regressions caused by the decoder change.

---

lib/decoders/decoders.cc
lib/decoders/decoders.h
lib/flux.h
lib/fluxsink/hardwarefluxsink.cc
lib/fluxsource/hardwarefluxsource.cc
lib/globals.h
lib/logger.cc
lib/logger.h
lib/reader.cc
lib/sector.cc
lib/sector.h
lib/writer.cc
mkninja.sh

Just writing out text files is okay for a CLI program, but won't work for the hypothetical GUI.

Overhaul the logging system

---

arch/mx/decoder.cc
lib/globals.h
lib/logger.cc
lib/logger.h

The new logger had mangled layout.
The MX decoder had an off-by-one error in the number of sectors per track.
Fixes: #466

Miscellaneous minor fixes

---

README.md
doc/building.md
doc/disk-acornadfs.md
doc/disk-acorndfs.md
doc/disk-aeslanier.md
doc/disk-ibm.md
doc/disk-micropolis.md
doc/using.md

Hi, I have fixed a few typos in documentation files only. Thanks :)

Fix various doc typos

---

README.md
arch/brother/encoder.cc
lib/writer.cc
src/formats/brother120.textpb

Reads and writes now work (according to my WP-1).

Fix the Brother 120kB format.

---

doc/disk-brother.md
lib/globals.h
lib/utils.cc
lib/utils.h
mkninja.sh
src/fluxengine.cc
src/gui/mainwindow.cc
tests/utils.cc
tools/brother120tool.cc
tools/brother240tool.cc
tools/upgrade-flux-file.cc

Add support for writing 120kB Brother disk images.

---

src/fe-write.cc

Fix regression with verification on writes.

---

lib/decoders/decoders.proto
lib/readerwriter.cc

This is useful for archiving.
See #492.

Allow an option to force the reader to read all tracks in a group.

---

lib/imagereader/imdimagereader.cc
src/formats/hplif770.textpb

Finally got around to adept the IMD reader to read an IMD image en set the protoconfiguration and be able to write it to physical media

Imd reader

---

.github/workflows/ccpp.yml
Makefile
src/fe-analysedriveresponse.cc
src/gui/build.mk

Fixes some odd build issues causing build failures on Ubuntu 20.
Fixes: #538

Make the build work on Ubuntu 20 again.

---

doc/using.md
lib/build.mk
lib/imagereader/imdimagereader.cc
lib/imagewriter/imagewriter.cc
lib/imagewriter/imagewriter.h
lib/imagewriter/imagewriter.proto
lib/imagewriter/imdimagewriter.cc
src/formats/hplif770.textpb
src/gui/mainwindow.cc

Changes in this pull request:
Add the ability to write imd images to file.
Update the documentation regarding the imd image possibilities.
make the HPLif format read and write
set the ibm format as default format in the gui version

add Imd writer option

---

.github/workflows/ccpp.yml

Looks like Homebrew truncate is no longer installable.

Fix CI builds on OSX.

---

lib/config.proto
lib/flags.cc
lib/flags.h
src/formats/_micropolis.textpb
src/formats/build.mk
src/formats/micropolis143.textpb
src/formats/micropolis287.textpb
src/formats/micropolis315.textpb
src/formats/micropolis630.textpb

This is useful for organisation, especially if there are multiple variants of each format.

Allow including config files from other config files.

---

Makefile
lib/build.mk
lib/vfs/cpmfs.cc
lib/vfs/vfs.cc
lib/vfs/vfs.h
lib/vfs/vfs.proto
src/fe-getfile.cc
src/formats/build.mk
src/formats/eco1.textpb
src/formats/epsonpf10.textpb

Add read-only support for CP/M file systems.

---

lib/bytes.cc
lib/bytes.h
lib/image.cc
lib/image.h
lib/readerwriter.cc
lib/readerwriter.h
lib/vfs/acorndfs.cc
lib/vfs/amigaffs.cc
lib/vfs/applesingle.cc
lib/vfs/brother120fs.cc
lib/vfs/cbmfs.cc
lib/vfs/fatfs.cc
lib/vfs/fluxsectorinterface.cc
lib/vfs/imagesectorinterface.cc
lib/vfs/machfs.cc
lib/vfs/sectorinterface.h
lib/vfs/vfs.cc
lib/vfs/vfs.h
lib/vfs/vfs.proto
src/build.mk
src/fe-putfile.cc
src/fe-write.cc
src/fileutils.cc
src/fluxengine.cc
src/gui/mainwindow.cc

...currently limited to just writing files, and in FATFS, HFS and FFS.

Add VFS write support.

---

lib/vfs/amigaffs.cc
lib/vfs/fatfs.cc
lib/vfs/machfs.cc
lib/vfs/vfs.cc
lib/vfs/vfs.h
src/build.mk
src/fe-format.cc
src/fluxengine.cc

Kinda clunky but works, on the filesystems which support writes.

Allow formatting disks.

---

lib/utils.cc
lib/utils.h
lib/vfs/acorndfs.cc
lib/vfs/amigaffs.cc
lib/vfs/brother120fs.cc
lib/vfs/cbmfs.cc
lib/vfs/cpmfs.cc
lib/vfs/fatfs.cc
lib/vfs/machfs.cc
lib/vfs/vfs.cc
lib/vfs/vfs.h
src/build.mk
src/fe-getdiskinfo.cc
src/fluxengine.cc

Including things like volume name, free space, etc.

Add filesystem metadata.

---

src/gui/mainwindow.cc

This got accidentally broken and I never noticed.

Make includes work in the GUI.

---

src/gui/mainwindow.cc

Remember to clear the config before loading a new one.

---

lib/imagewriter/imagewriter.cc
lib/vfs/acorndfs.cc
lib/vfs/amigaffs.cc
lib/vfs/brother120fs.cc
lib/vfs/cbmfs.cc
lib/vfs/cpmfs.cc
lib/vfs/fatfs.cc
lib/vfs/machfs.cc
src/gui/mainwindow.cc

Add put and delete support for the Brother120 filesystem.

---

arch/ibm/decoder.cc
arch/ibm/encoder.cc
arch/ibm/ibm.h
arch/ibm/ibm.proto
lib/encoders/encoders.cc
lib/encoders/encoders.h
lib/encoders/encoders.proto
lib/layout.proto
lib/readerwriter.cc
lib/sector.h
src/formats/commodore1581.textpb

The last fix didn't work; this one seems to be more robust.
Fixes: #413

Another attempt at fixing the C64 1581 bug.

---

lib/imagewriter/imdimagewriter.cc

#598 the flags in this function where not adjusted what resulted in the mentioned error. Hope this fixes it.

bug fix in data rates

---

lib/imagereader/d88imagereader.cc
lib/imagereader/nfdimagereader.cc

This fixes #560 (partially).
I do not understand how the protobuf parsing stuff works enough
to make it detect optional fields.

Force density setting for D88/NFD.

---

lib/layout.cc
src/formats/ibm.textpb

The layout cache is busted and seems not worth the effort.
Fixes #603.

Remove the layout cache and rename layout -> trackInfo.

---

lib/common.proto
lib/config.proto
lib/proto.cc

Recursive fields make recursive searches sad.
Fixes: #609

Fix --doc to not hang.

---

lib/utils.cc
lib/utils.h
lib/vfs/fatfs.cc
lib/vfs/vfs.cc

Incorrect types were being used when returning values to disk_ioctl. Ah, C type system, you're so special...
Fixes: #602

Fix weird error when trying to create fatfs filesystems.

---

doc/disk-smaky6.md
doc/filesystem.md
lib/build.mk
lib/vfs/smaky6fs.cc
lib/vfs/vfs.cc
lib/vfs/vfs.h
lib/vfs/vfs.proto
src/formats/smaky6.textpb
src/gui/fileviewerwindow.cc

This allows directory listing and reading files only --- and I'm not even sure that reading files works properly.

Add basic filesystem support for the Smaky 6.

---

lib/decoders/fluxmapreader.cc
lib/decoders/fluxmapreader.h
src/gui/fluxviewercontrol.cc

It now shows decoded raw bits in the timeline view.

Improve the flux viewer.

---

arch/macintosh/encoder.cc
lib/layout.cc
src/formats/mac400.textpb
tests/layout.cc

Turns out that the algorithm for calculating it was completely broken.
Also, tweak the mac timings to make them more like the real thing.

Fix sector skew, again.

---

src/formats/build.mk
src/formats/tiki200.textpb
src/formats/tiki400.textpb
src/formats/tiki800.textpb
src/formats/tiki90.textpb

This is a fairly sensible CP/M machine with four formats on 5.25" disks.

Add support for the Tiki 100 formats.

---

Makefile
README.md
arch/apple2/apple2.proto
arch/apple2/decoder.cc
arch/apple2/encoder.cc
doc/disk-apple2.md
lib/build.mk
lib/vfs/appledos.cc
lib/vfs/vfs.cc
lib/vfs/vfs.h
lib/vfs/vfs.proto
src/formats/_apple2.textpb
src/formats/apple2.textpb
src/formats/appleii140.textpb
src/formats/appleii640.textpb
src/formats/build.mk

Add support for the Basis-108 Apple II clone.

---

.github/workflows/ccpp.yml

Apparently the current version doesn't run on it.

Add support for OSX 10.15.

---

lib/utils.cc
lib/utils.h
lib/vfs/lif.cc
tests/utils.cc

You now have:
- textual file types
- ctime extraction
- all the LIF dirent custom properties

Do some LIF enhancement.

---

.github/workflows/ccpp.yml
Makefile
src/formats/acorndfs.textpb
src/formats/ampro.textpb
src/formats/atarist.textpb
src/formats/mac.textpb
src/formats/micropolis.textpb
src/formats/victor9k.textpb
tests/build.mk
tests/configs.cc

This now does basic sanity testing of the configs, and will attempt to decode the test corpus to detect regressions.

Do more options overhauling.

---

lib/logger.cc
lib/usb/greaseweazleusb.cc
lib/usb/serial.cc
lib/usb/serial.h

This avoids those annoying sync errors.

Reset the Greaseweazle data stream when connecting

---

build.py
build/ab.py
build/pkg.py
src/gui/build.py

Update ab. You can now build individual tools individually.

---

doc/using.md
src/build.py
src/fe-rpm.cc
src/fe-testdevices.cc
src/fluxengine.cc

Also fixes a bug in the rpm command.
Fixes: #740

Add a command to list detectable devices on the command line.

---

lib/fluxsink/a2rfluxsink.cc

It's still not right, but it's better.

Improve the A2R writer.

---

.github/workflows/ccpp.yml
Makefile
lib/data/sector.h
tests/docker/Dockerfile.debian11
tests/docker/Dockerfile.debian12

Also add some Docker tests to make sure it keeps working.
Fixes: #788

Make work on Debian 11.

---

src/formats/build.py
src/formats/juku.textpb

Add 800kB/400kB Juku E5104 floppies to exemplarily close issue #795

Add Juku E5104 floppy formats

---

.github/workflows/ccpp.yml
.github/workflows/release.yml
build.py
src/gui/build.py

Expose the .app on OSX (in a zipfile).
